import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.*;

/**
 * @author maglangitsd
 */
public class PointOfSale extends javax.swing.JFrame {
    private final int VM1_PRICE = 30;
    private final int VM2_PRICE = 60;
    private final int VM3_PRICE = 70;
    private final int VM4_PRICE = 90;
    private final int VM5_PRICE = 105;
    private final int VM6_PRICE = 150;
    private final double DISCOUNT = 0.2;

    private ArrayList<Meal> meals = new ArrayList<>();
    private DefaultListModel listModel = new DefaultListModel();

    private String discountId;
    private String cardNumber;
    JRadioButton previouslySelectedDiscount;
    JRadioButton previouslySelectedPayment;

    /**
     * Creates new form PointOfSale
     */
    public PointOfSale() {
        initComponents();
        lblId.setVisible(false);
        previouslySelectedDiscount = rbtnNone;
        previouslySelectedPayment = rbtnCash;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgDiscount = new javax.swing.ButtonGroup();
        bgPayment = new javax.swing.ButtonGroup();
        pnlDiscount = new javax.swing.JPanel();
        lblDiscount = new javax.swing.JLabel();
        rbtnNone = new javax.swing.JRadioButton();
        rbtnSC = new javax.swing.JRadioButton();
        rbtnPWD = new javax.swing.JRadioButton();
        lblId = new javax.swing.JLabel();
        pnlPayment = new javax.swing.JPanel();
        lblPayment = new javax.swing.JLabel();
        rbtnCash = new javax.swing.JRadioButton();
        rbtnDebit = new javax.swing.JRadioButton();
        rbtnCredit = new javax.swing.JRadioButton();
        lblTotal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnVM1 = new javax.swing.JButton();
        btnVM2 = new javax.swing.JButton();
        btnVM3 = new javax.swing.JButton();
        btnVM4 = new javax.swing.JButton();
        btnVM5 = new javax.swing.JButton();
        btnVM6 = new javax.swing.JButton();
        scrollOrder = new javax.swing.JScrollPane();
        listOrder = new javax.swing.JList<>();
        btnDelete = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        cbxOut = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDiscount.setText("Discount");

        bgDiscount.add(rbtnNone);
        rbtnNone.setSelected(true);
        rbtnNone.setText("None");
        rbtnNone.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                rbtnNoneActionPerformed(evt);
            }
        });

        bgDiscount.add(rbtnSC);
        rbtnSC.setText("SC");
        rbtnSC.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                rbtnSCActionPerformed(evt);
            }
        });

        bgDiscount.add(rbtnPWD);
        rbtnPWD.setText("PWD");
        rbtnPWD.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                rbtnPWDActionPerformed(evt);
            }
        });

        lblId.setText("ID");

        javax.swing.GroupLayout pnlDiscountLayout = new javax.swing.GroupLayout(pnlDiscount);
        pnlDiscount.setLayout(pnlDiscountLayout);
        pnlDiscountLayout.setHorizontalGroup(
                pnlDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlDiscountLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbtnSC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rbtnNone, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                        .addComponent(rbtnPWD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pnlDiscountLayout.createSequentialGroup()
                                                .addComponent(lblDiscount)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlDiscountLayout.setVerticalGroup(
                pnlDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlDiscountLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDiscount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnNone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnSC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnPWD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblId)
                                .addContainerGap(8, Short.MAX_VALUE))
        );

        lblPayment.setText("Payment");

        bgPayment.add(rbtnCash);
        rbtnCash.setSelected(true);
        rbtnCash.setText("Cash");
        rbtnCash.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                rbtnCashActionPerformed(evt);
            }
        });

        bgPayment.add(rbtnDebit);
        rbtnDebit.setText("Debit");
        rbtnDebit.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                rbtnDebitActionPerformed(evt);
            }
        });

        bgPayment.add(rbtnCredit);
        rbtnCredit.setText("Credit");
        rbtnCredit.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                rbtnCreditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPaymentLayout = new javax.swing.GroupLayout(pnlPayment);
        pnlPayment.setLayout(pnlPaymentLayout);
        pnlPaymentLayout.setHorizontalGroup(
                pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rbtnDebit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtnCash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtnCredit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPaymentLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblPayment)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPaymentLayout.setVerticalGroup(
                pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlPaymentLayout.createSequentialGroup()
                                .addComponent(lblPayment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnCash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnDebit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnCredit)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTotal.setText("Total: Php 0");

        btnVM1.setText("VM1");
        btnVM1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnVM1ActionPerformed(evt);
            }
        });

        btnVM2.setText("VM2");
        btnVM2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnVM2ActionPerformed(evt);
            }
        });

        btnVM3.setText("VM3");
        btnVM3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnVM3ActionPerformed(evt);
            }
        });

        btnVM4.setText("VM4");
        btnVM4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnVM4ActionPerformed(evt);
            }
        });

        btnVM5.setText("VM5");
        btnVM5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnVM5ActionPerformed(evt);
            }
        });

        btnVM6.setText("VM6");
        btnVM6.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnVM6ActionPerformed(evt);
            }
        });

        listOrder.setModel(listModel);
        scrollOrder.setViewportView(listOrder);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnContinue.setText("Continue");
        btnContinue.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnContinue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(scrollOrder)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btnVM4, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                                        .addComponent(btnVM1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(9, 9, 9)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btnVM2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnVM5, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btnVM6, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                                        .addComponent(btnVM3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(12, 12, 12))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{btnVM4, btnVM5, btnVM6});

        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnVM1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnVM2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnVM3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnVM4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnVM5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnVM6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnContinue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );

        cbxOut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Dine In", "Cash out"}));
        cbxOut.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cbxOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbxOut, 0, 100, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(pnlPayment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(pnlDiscount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnlDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTotal)
                                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int getOrderQuantity() {
        String quantity = JOptionPane.showInputDialog(null, "Enter Quantity", "Quantity", JOptionPane.INFORMATION_MESSAGE);

        if (quantity == null) {
            return 0;
        } else if (Integer.parseInt(quantity) <= 0) {
            JOptionPane.showMessageDialog(null, "Quantity must be at least 1", "ID Error", JOptionPane.ERROR_MESSAGE);
            return getOrderQuantity();
        } else return Integer.parseInt(quantity);
    }

    private void updateTotal() {
        int total = 0;
        for (Meal meal : meals) total += meal.getTotal();
        lblTotal.setText("Total: Php " + total);
    }

    private void getDiscountId() {
        String id = JOptionPane.showInputDialog(null, "Enter Discount ID", "Discount ID", JOptionPane.INFORMATION_MESSAGE);

        if (id == null) {
            previouslySelectedDiscount.setSelected(true);
        } else if (!id.matches("\\b\\d+\\b")) {
            JOptionPane.showMessageDialog(null, "ID must only contain numberical characters", "ID Error", JOptionPane.ERROR_MESSAGE);
            getDiscountId();
        } else if (id.length() != 5) {
            JOptionPane.showMessageDialog(null, "ID must have only 5 characters", "ID Error", JOptionPane.ERROR_MESSAGE);
            getDiscountId();
        } else {
            if (rbtnSC.isSelected()) previouslySelectedDiscount = rbtnSC;
            else if (rbtnPWD.isSelected()) previouslySelectedDiscount = rbtnPWD;

            discountId = id;
            lblId.setText("ID: " + id);
            lblId.setVisible(true);
        }
    }

    private void getCCInformation() {
        String number = JOptionPane.showInputDialog(null, "Enter Card Number", "Card Number", JOptionPane.INFORMATION_MESSAGE);

        if (number == null) {
            previouslySelectedPayment.setSelected(true);
        } else if (number.length() != 16) {
            JOptionPane.showMessageDialog(null, "ID must have 16 characters", "Card Number Error", JOptionPane.ERROR_MESSAGE);
            getCCInformation();
        } else {
            if (rbtnDebit.isSelected()) previouslySelectedPayment = rbtnDebit;
            else if (rbtnCredit.isSelected()) previouslySelectedPayment = rbtnCredit;
            cardNumber = number;
        }
    }

    private void addOrder(OrderType type) {
        Meal meal;
        int quantity = getOrderQuantity();
        int price = 0;

        if (quantity == 0) return;

        switch (type) {
            case VM1:
                price = VM1_PRICE;
            case VM2:
                price = VM2_PRICE;
            case VM3:
                price = VM3_PRICE;
            case VM4:
                price = VM4_PRICE;
            case VM5:
                price = VM5_PRICE;
            case VM6:
                price = VM6_PRICE;
        }

        meal = new Meal(quantity, type.name(), price);
        meals.add(meal);
        listModel.addElement(meal.toString());
        updateTotal();
    }

    private void resetState() {
        listModel.clear();
        meals.clear();
        cardNumber = "";
        discountId = "";
        previouslySelectedDiscount = rbtnNone;
        previouslySelectedPayment = rbtnCash;
        lblTotal.setText("Total: Php 0");
        rbtnNone.setSelected(true);
        rbtnCash.setSelected(true);
        lblId.setVisible(false);
        cbxOut.setSelectedIndex(0);
    }

    private void btnVM1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnVM1ActionPerformed
        addOrder(OrderType.VM1);
    }//GEN-LAST:event_btnVM1ActionPerformed

    private void btnVM2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnVM2ActionPerformed
        addOrder(OrderType.VM2);
    }//GEN-LAST:event_btnVM2ActionPerformed

    private void btnVM3ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnVM3ActionPerformed
        addOrder(OrderType.VM3);
    }//GEN-LAST:event_btnVM3ActionPerformed

    private void btnVM4ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnVM4ActionPerformed
        addOrder(OrderType.VM4);
    }//GEN-LAST:event_btnVM4ActionPerformed

    private void btnVM5ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnVM5ActionPerformed
        addOrder(OrderType.VM5);
    }//GEN-LAST:event_btnVM5ActionPerformed

    private void btnVM6ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnVM6ActionPerformed
        addOrder(OrderType.VM6);
    }//GEN-LAST:event_btnVM6ActionPerformed

    private void btnDeleteActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            meals.remove(listOrder.getSelectedIndex());
            listModel.remove(listOrder.getSelectedIndex());
            updateTotal();
        } catch (Exception e) {
            String errorMessage = "";
            if (listModel.isEmpty()) errorMessage = "No order has been made yet";
            else errorMessage = "No item has been selected.";

            JOptionPane.showMessageDialog(null, errorMessage, "Order Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void rbtnPWDActionPerformed(ActionEvent evt) {//GEN-FIRST:event_rbtnPWDActionPerformed
        getDiscountId();
    }//GEN-LAST:event_rbtnPWDActionPerformed

    private void rbtnSCActionPerformed(ActionEvent evt) {//GEN-FIRST:event_rbtnSCActionPerformed
        getDiscountId();
    }//GEN-LAST:event_rbtnSCActionPerformed

    private void rbtnNoneActionPerformed(ActionEvent evt) {//GEN-FIRST:event_rbtnNoneActionPerformed
        previouslySelectedDiscount = rbtnNone;
        lblId.setVisible(false);
    }//GEN-LAST:event_rbtnNoneActionPerformed

    private void cbxOutActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cbxOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxOutActionPerformed

    private void btnContinueActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        String receiptMessage;
        int numberOfOrders = 0;
        int total = 0;
        double discount;

        if (meals.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No order has been made yet", "Order Error", JOptionPane.ERROR_MESSAGE);
        } else {
            for (Meal meal : meals) numberOfOrders += meal.getQuantity();
            for (Meal meal : meals) total += meal.getTotal();

            receiptMessage =
                    "Number of Orders: " + numberOfOrders + "\n" +
                            "Subtotal: Php " + total + "\n";

            if (rbtnSC.isSelected() || rbtnPWD.isSelected()) {
                discount = total * DISCOUNT;
                receiptMessage +=
                        "Discount: " + discountId + "\n" +
                                "                    " + discount + "\n" +
                                "Total: " + (total - discount) + "\n";
            } else {
                receiptMessage += "Total: Php " + total + "\n";
            }

            if (rbtnCash.isSelected()) receiptMessage += "Payment: Cash\n";
            else if (rbtnDebit.isSelected()) receiptMessage += "Payment: Debit \n" + cardNumber + "\n";
            else if (rbtnCredit.isSelected()) receiptMessage += "Payment: Credit \n" + cardNumber + "\n";

            receiptMessage += cbxOut.getSelectedItem().toString();

            JOptionPane.showMessageDialog(null, receiptMessage, "Receipt", JOptionPane.PLAIN_MESSAGE);

            resetState();
        }
    }//GEN-LAST:event_btnContinueActionPerformed

    private void rbtnCashActionPerformed(ActionEvent evt) {//GEN-FIRST:event_rbtnCashActionPerformed
        previouslySelectedPayment = rbtnCash;
        cardNumber = "";
    }//GEN-LAST:event_rbtnCashActionPerformed

    private void rbtnDebitActionPerformed(ActionEvent evt) {//GEN-FIRST:event_rbtnDebitActionPerformed
        getCCInformation();
    }//GEN-LAST:event_rbtnDebitActionPerformed

    private void rbtnCreditActionPerformed(ActionEvent evt) {//GEN-FIRST:event_rbtnCreditActionPerformed
        getCCInformation();
    }//GEN-LAST:event_rbtnCreditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PointOfSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PointOfSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PointOfSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PointOfSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PointOfSale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgDiscount;
    private javax.swing.ButtonGroup bgPayment;
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnVM1;
    private javax.swing.JButton btnVM2;
    private javax.swing.JButton btnVM3;
    private javax.swing.JButton btnVM4;
    private javax.swing.JButton btnVM5;
    private javax.swing.JButton btnVM6;
    private javax.swing.JComboBox<String> cbxOut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JList<String> listOrder;
    private javax.swing.JPanel pnlDiscount;
    private javax.swing.JPanel pnlPayment;
    private javax.swing.JRadioButton rbtnCash;
    private javax.swing.JRadioButton rbtnCredit;
    private javax.swing.JRadioButton rbtnDebit;
    private javax.swing.JRadioButton rbtnNone;
    private javax.swing.JRadioButton rbtnPWD;
    private javax.swing.JRadioButton rbtnSC;
    private javax.swing.JScrollPane scrollOrder;
    // End of variables declaration//GEN-END:variables
}
